CREATE DATABASE user_db;

\c user_db;

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE posts (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);

INSERT INTO users (name, email, password) VALUES 
    ('Luiz', 'Luiz@gmail.com', 'amods'),
    ('lucas', 'luccas@gmail.com', 'amods'),
    ('João', 'joao@gmail.com', 'amods'),
    ('Maria', 'maria@gmail.com', 'amods'),
    ('Ana', 'ana@gmail.com', 'amods'),
    ('Pedro', 'pedro@gmail.com', 'amods'),
    ('Carlos', 'carlos@gmail.com', 'amods'),
    ('Fernanda', 'fernanda@gmail.com', 'amods'),
    ('Juliana', 'juliana@gmail.com', 'amods'),
    ('Roberto', 'roberto@gmail.com', 'amods'),
    ('Patrícia', 'patricia@gmail.com', 'amods'),
    ('Mariana', 'mariana@gmail.com', 'amods'),
    ('Ricardo', 'ricardo@gmail.com', 'amods'),
    ('Tatiane', 'tatiane@gmail.com', 'amods'),
    ('Gustavo', 'gustavo@gmail.com', 'amods'),
    ('Sofia', 'sofia@gmail.com', 'amods'),
    ('Rafael', 'rafael@gmail.com', 'amods'),
    ('Isabela', 'isabela@gmail.com', 'amods'),
    ('Leonardo', 'leonardo@gmail.com', 'amods'),
    ('Camila', 'camila@gmail.com', 'amods'),
    ('Felipe', 'felipe@gmail.com', 'amods'),
    ('Bruna', 'bruna@gmail.com', 'amods'),
    ('Eduardo', 'eduardo@gmail.com', 'amods'),
    ('Tatiane', 'tati@gmail.com', 'amods'),
    ('Thiago', 'thiago@gmail.com', 'amods'),
    ('Larissa', 'larissa@gmail.com', 'amods'),
    ('André', 'andre@gmail.com', 'amods'),
    ('Vanessa', 'vanessa@gmail.com', 'amods'),
    ('Marcos', 'marcos@gmail.com', 'amods'),
    ('Aline', 'aline@gmail.com', 'amods'),
    ('Bruno', 'bruno@gmail.com', 'amods'),
    ('Natália', 'natalia@gmail.com', 'amods'),
    ('Diego', 'diego@gmail.com', 'amods'),
    ('Patrícia', 'paty@gmail.com', 'amods'),
    ('Juliano', 'juliano@gmail.com', 'amods'),
    ('Cecília', 'cecilia@gmail.com', 'amods'),
    ('Samuel', 'samuel@gmail.com', 'amods'),
    ('Alice', 'alice@gmail.com', 'amods'),
    ('Joana', 'joana@gmail.com', 'amods'),
    ('Henrique', 'henrique@gmail.com', 'amods'),
    ('Gabriela', 'gabriela@gmail.com', 'amods'),
    ('Rodrigo', 'rodrigo@gmail.com', 'amods'),
    ('Beatriz', 'beatriz@gmail.com', 'amods'),
    ('Eduarda', 'eduarda@gmail.com', 'amods'),
    ('Rafaela', 'rafaela@gmail.com', 'amods'),
    ('Vinícius', 'vinicius@gmail.com', 'amods'),
    ('Matheus', 'matheus@gmail.com', 'amods'),
    ('Carolina', 'carolina@gmail.com', 'amods'),
    ('Luana', 'luana@gmail.com', 'amods'),
    ('Marcelo', 'marcelo@gmail.com', 'amods'),
    ('Paula', 'paula@gmail.com', 'amods');

INSERT INTO posts (title, content, user_id) VALUES 
    ('Post 1', 'Conteúdo do post 1', 1),
    ('Post 2', 'Conteúdo do post 2', 2),
    ('Post 3', 'Conteúdo do post 3', 3),
    ('Post 4', 'Conteúdo do post 4', 4),
    ('Post 5', 'Conteúdo do post 5', 5),
    ('Post 6', 'Conteúdo do post 6', 6),
    ('Post 7', 'Conteúdo do post 7', 7),
    ('Post 8', 'Conteúdo do post 8', 8),
    ('Post 9', 'Conteúdo do post 9', 9),
    ('Post 10', 'Conteúdo do post 10', 10),
    ('Post 11', 'Conteúdo do post 11', 11),
    ('Post 12', 'Conteúdo do post 12', 12),
    ('Post 13', 'Conteúdo do post 13', 13),
    ('Post 14', 'Conteúdo do post 14', 14),
    ('Post 15', 'Conteúdo do post 15', 15),
    ('Post 16', 'Conteúdo do post 16', 16),
    ('Post 17', 'Conteúdo do post 17', 17),
    ('Post 18', 'Conteúdo do post 18', 18),
    ('Post 19', 'Conteúdo do post 19', 19),
    ('Post 20', 'Conteúdo do post 20', 20),
    ('Post 21', 'Conteúdo do post 21', 21),
    ('Post 22', 'Conteúdo do post 22', 22),
    ('Post 23', 'Conteúdo do post 23', 23),
    ('Post 24', 'Conteúdo do post 24', 24),
    ('Post 25', 'Conteúdo do post 25', 25),
    ('Post 26', 'Conteúdo do post 26', 26),
    ('Post 27', 'Conteúdo do post 27', 27),
    ('Post 28', 'Conteúdo do post 28', 28),
    ('Post 29', 'Conteúdo do post 29', 29),
    ('Post 30', 'Conteúdo do post 30', 30),
    ('Post 31', 'Conteúdo do post 31', 31),
    ('Post 32', 'Conteúdo do post 32', 32),
    ('Post 33', 'Conteúdo do post 33', 33),
    ('Post 34', 'Conteúdo do post 34', 34),
    ('Post 35', 'Conteúdo do post 35', 35),
    ('Post 36', 'Conteúdo do post 36', 36),
    ('Post 37', 'Conteúdo do post 37', 37),
    ('Post 38', 'Conteúdo do post 38', 38),
    ('Post 39', 'Conteúdo do post 39', 39),
    ('Post 40', 'Conteúdo do post 40', 40),
    ('Post 41', 'Conteúdo do post 41', 41),
    ('Post 42', 'Conteúdo do post 42', 42),
    ('Post 43', 'Conteúdo do post 43', 43),
    ('Post 44', 'Conteúdo do post 44', 44),
    ('Post 45', 'Conteúdo do post 45', 45),
    ('Post 46', 'Conteúdo do post 46', 46),
    ('Post 47', 'Conteúdo do post 47', 47),
    ('Post 48', 'Conteúdo do post 48', 48),
    ('Post 49', 'Conteúdo do post 49', 49),
    ('Post 50', 'Conteúdo do post 50', 50);